WebStore/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebStore.Controllers
{

    public class BlogController : Controller
    {

        public IActionResult List() => View();

        public IActionResult Single() => View();

    }
}

WebStore/Controllers/CartController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Language;
using WebStore.Entities;
using WebStore.Entities.Identity;
using WebStore.Interfaces;
using WebStore.ViewModels;

namespace WebStore.Controllers
{

    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly IProductsService _productsService;

        public CartController(ICartService cartService, IProductsService productsService)
        {
            _cartService = cartService;
            _productsService = productsService;
        }

        public IActionResult Index()
        {
            var model = new CartOrderViewModel
            {
                Cart = GetCartViewModel()
            };

            return View(model);
        }

        public IActionResult Add(int id)
        {
            _cartService.Add(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(int id)
        {
            _cartService.Remove(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Decrement(int id)
        {
            _cartService.Decrement(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Clear()
        {
            _cartService.Clear();
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> CheckOut(
            OrderViewModel orderModel,
            [FromServices] IOrdersService ordersService,
            [FromServices] UserManager<User> userManager)
        {
            var cartModel = GetCartViewModel();

            if (!ModelState.IsValid)
            {
                return View(nameof(Index), new CartOrderViewModel
                {
                    Cart = cartModel,
                    Order = orderModel
                });

            }
            var userName = User.Identity?.Name;
            var user = await userManager.FindByNameAsync(userName);
            if (user is null)
                throw new InvalidOperationException($"User {userName} is not found.");

            var order = CreateOrder(user, cartModel, orderModel);
            await ordersService.Add(order);

            _cartService.Clear();
            return RedirectToAction(nameof(OrderConfirmed), new { order.Id });
        }

        public IActionResult OrderConfirmed(int id)
        {
            ViewBag.OrderId = id;
            return View();
        }

        private Order CreateOrder(User user, CartViewModel cartModel, OrderViewModel orderModel)
        {
            var order = new Order
            {
                Name = orderModel.Name,
                Phone = orderModel.Phone,
                Address = orderModel.Address,
                User = user
            };

            var cart_products = _productsService.GetProducts(new ProductFilter
            {
                Ids = cartModel.Items.Select(x => x.Product.Id).ToArray()
            });

            order.Items = cartModel.Items.Join(
                cart_products,
                cart_item => cart_item.Product.Id,
                product => product.Id,
                (cart_item, product) => new OrderItem
                {
                    Order = order,
                    Product = product,
                    Quantity = cart_item.Quantity,
                    Price = product.Price
                }).ToArray();

            return order;
        }

        private CartViewModel GetCartViewModel()
        {
            var cart = _cartService.Cart;

            var products = _productsService.GetProducts(new ProductFilter
            {
                Ids = cart.Items.Select(item => item.ProductId).ToArray()
            });

            return cart.ToView(products);
        }

    }
}

WebStore/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using WebStore.Interfaces;
using WebStore.ViewModels;

namespace WebStore.Controllers
{

    public class CatalogController : Controller
    {

        private readonly IProductsService _productsService;

        public CatalogController(IProductsService productsService) => _productsService = productsService;

        public IActionResult Index(int? categoryId, int? brandId)
        {
            ProductFilter filter = new() { CategoryId = categoryId, BrandId = brandId };

            var products = _productsService.GetProducts(filter);

            return View(new CatalogViewModel
            {
                CategoryId = categoryId,
                BrandId = brandId,
                Products = products.OrderBy(p => p.OrderNumber).ToView()
            });
        }

        public IActionResult Details(int id) =>
            View(_productsService.GetProduct(id).ToView());

    }
}

WebStore/Controllers/EmployeesController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebStore.Entities.Identity;
using WebStore.Interfaces;
using WebStore.Models;
using WebStore.ViewModels;

namespace WebStore.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    {

        private readonly IEmployeesService _employeesService;

        public EmployeesController(IEmployeesService employeesService)
        {
            _employeesService = employeesService;
        }

        private IActionResult ViewById(int id) => id switch
        {
            <= 0 => BadRequest(),
            > 0 => _employeesService.Get(id) switch
            {
                null => NotFound(),
                Employee e => View(new EmployeeViewModel(e))
            }
        };

        public IActionResult Index() => View(_employeesService.Get());

        public IActionResult Details(int id) => ViewById(id);

        [Authorize(Roles = Role.Administrator)]
        public IActionResult Create() => View("Edit", new EmployeeViewModel());

        [Authorize(Roles = Role.Administrator)]
        public IActionResult Edit(int id) => ViewById(id);

        [Authorize(Roles = Role.Administrator)]
        public IActionResult Delete(int id) => ViewById(id);

        [HttpPost]
        [Authorize(Roles = Role.Administrator)]
        public IActionResult Edit(EmployeeViewModel model)
        {
            Action<Employee> action = model switch
            {
                null => throw new ArgumentNullException(nameof(model)),
                _ => ModelState.IsValid switch
                {
                    false => null,
                    true => model.Id switch
                    {
                        0 => _employeesService.Add,
                        _ => _employeesService.Update
                    }
                }
            };
            if (action is null)
                return View(model);
            else
            {
                action.Invoke(model.Employee);
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [Authorize(Roles = Role.Administrator)]
        public IActionResult DeleteConfirmed(int id) => id switch
        {
            <= 0 => BadRequest(),
            > 0 => _employeesService.Delete(id) switch
            {
                false => NotFound(),
                true => RedirectToAction("Index")
            }
        };
    }
}

WebStore/Views/Shared/Partial/_Footer.cshtml
<footer id="footer">
    <!--Footer-->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="companyinfo">
                        <h2><span>e</span>-shopper</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe1.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe2.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe3.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe4.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="address">
                        <img src="~/images/home/map.png" alt="" />
                        <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Service</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Online Help</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Order Status</a></li>
                            <li><a href="#">Change Location</a></li>
                            <li><a href="#">FAQ’s</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Quock Shop</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">T-Shirt</a></li>
                            <li><a href="#">Mens</a></li>
                            <li><a href="#">Womens</a></li>
                            <li><a href="#">Gift Cards</a></li>
                            <li><a href="#">Shoes</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Policies</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Terms of Use</a></li>
                            <li><a href="#">Privecy Policy</a></li>
                            <li><a href="#">Refund Policy</a></li>
                            <li><a href="#">Billing System</a></li>
                            <li><a href="#">Ticket System</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Company Information</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Store Location</a></li>
                            <li><a href="#">Affillate Program</a></li>
                            <li><a href="#">Copyright</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3 col-sm-offset-1">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <form action="#" class="searchform">
                            <input type="text" placeholder="Your email address" />
                            <button type="submit" class="btn btn-default"><i
                                    class="fa fa-arrow-circle-o-right"></i></button>
                            <p>Get the most recent updates from <br />our site and be updated your self...</p>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
                <p class="pull-right">Designed by <span><a target="_blank"
                            href="http://www.themeum.com">Themeum</a></span></p>
            </div>
        </div>
    </div>

</footer>
<!--/Footer-->

WebStore/Views/Shared/Partial/_Header.cshtml
<header id="header">
    <!--header-->
    <div class="header_top">
        <!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/header_top-->

    <div class="header-middle">
        <!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        <a href="index.html"><img src="~/images/home/logo.png" alt="" /></a>
                    </div>
                    <div class="btn-group pull-right">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                USA
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canada</a></li>
                                <li><a href="#">UK</a></li>
                            </ul>
                        </div>

                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                DOLLAR
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canadian Dollar</a></li>
                                <li><a href="#">Pound</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <vc:user-info />
                </div>
            </div>
        </div>
    </div>
    <!--/header-middle-->

    <div class="header-bottom">
        <!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <partial name="Partial/_MainMenu" />
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="Search" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/header-bottom-->
</header>
<!--/header-->

WebStore/Views/Shared/Partial/_Icons.cshtml
<link rel="shortcut icon" href="images/ico/favicon.ico">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">

WebStore/Views/Shared/Partial/_MainMenu.cshtml
<ul class="nav navbar-nav collapse navbar-collapse">
    <li><a asp-controller="Home" asp-action="Index" class="active">Home</a></li>
    <li class="dropdown">
        <a href="#">Shop<i class="fa fa-angle-down"></i></a>
        <ul role="menu" class="sub-menu">
            <li><a asp-controller="Catalog" asp-action="Index">Products</a></li>
            <li><a asp-controller="Catalog" asp-action="Details">Product Details</a></li>
            <li><a asp-controller="Cart" asp-action="CheckOut">Checkout</a></li>
            <li><a asp-controller="Cart" asp-action="Index">Cart</a></li>
            <li><a asp-controller="Account" asp-action="Login">Login</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#">Blog<i class="fa fa-angle-down"></i></a>
        <ul role="menu" class="sub-menu">
            <li><a asp-controller="Blog" asp-action="List">Blog List</a></li>
            <li><a asp-controller="Blog" asp-action="Single">Blog Single</a></li>
        </ul>
    </li>
    <li><a asp-controller="Error" asp-action="Error404">404</a></li>
    <li><a asp-controller="Home" asp-action="ContactUs">Contact</a></li>
    <li><a asp-controller="Employees" asp-action="Index">Employees</a></li>
</ul>

WebStore/Views/Shared/Partial/_Scripts.cshtml
<script src="~/js/jquery.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/jquery.scrollUp.min.js"></script>
<script src="~/js/jquery.prettyPhoto.js"></script>


<environment include="Development">
    <script src="~/js/price-range.js" asp-append-version="true"></script>
    <script src="~/js/main.js" asp-append-version="true"></script>
</environment>

<environment exclude="Development">
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

WebStore/Views/Shared/Partial/_Styles.cshtml
<link href="~/css/bootstrap.min.css" rel="stylesheet">
<link href="~/css/font-awesome.min.css" rel="stylesheet">
<link href="~/css/prettyPhoto.css" rel="stylesheet">

<!--[if lt IE 9]>
    <script src="~/js/html5shiv.js"></script>
    <script src="~/js/respond.min.js"></script>
    <![endif]-->

<environment include="Development">
    <link href="~/css/price-range.css" rel="stylesheet" asp-append-version="true">
    <link href="~/css/animate.css" rel="stylesheet" asp-append-version="true">
    <link href="~/css/main.css" rel="stylesheet" asp-append-version="true">
    <link href="~/css/responsive.css" rel="stylesheet" asp-append-version="true">
</environment>

<environment exclude="Development">
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true">
</environment>